// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kadhfnujbszohuashfsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthZGhmbnVqYnN6b2h1YXNoZnNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMzIzODQsImV4cCI6MjA2MzgwODM4NH0.qur5prS3iZVOKRou6Yk_fCS2-0l3ZROIbhvGch634hc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);